cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/util/AbstractConfiguration.java
cadc-util/src/main/java/ca/nrc/cadc/util/DOMTreeErrorReporter.java
cadc-util/src/main/java/ca/nrc/cadc/util/LoggerUtil.java
cadc-util/src/main/java/ca/nrc/cadc/util/UsageException.java
cadc-util/src/main/java/ca/nrc/cadc/util/XmlConfigReader.java
cadc-util/src/test/java/ca/nrc/cadc/util/AllTypesConfig.java
cadc-util/src/test/java/ca/nrc/cadc/util/Config.java
cadc-util/src/test/java/ca/nrc/cadc/util/ExpectationConfig.java
cadc-util/src/test/java/ca/nrc/cadc/util/LoggerUtilTest.java
cadc-util/src/test/java/ca/nrc/cadc/util/StructInList.java
cadc-util/src/test/java/ca/nrc/cadc/util/XmlConfigReaderTest.java

Fixed some javadoc errors as well.

Added LoggerUtil from wbase/javaUtil

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/HttpDelete.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpTransfer.java
cadc-util/src/test/java/ca/nrc/cadc/net/HttpDeleteTest.java

Added HttpDelete class as a reusable means to issue HTTP DELETE methods.

For Issue #11 in opencadc/vos

---

cadc-log/build.gradle
cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java

when accessGroup is configured

cadc-log-1.0.1: attempt to find ctor(String) and call it 

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/util/ArgumentMap.java
cadc-util/src/test/java/ca/nrc/cadc/util/ArgumentMapTest.java

… -) in a list to preserve order

added support for ArgumentMap to store non-option command-line args

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/xml/JsonOutputter.java
cadc-util/src/test/java/ca/nrc/cadc/xml/JsonOutputterTest.java

Reverts opencadc/core#35 - Problem is in the cadc-access-control json writer, not this outputter.

Revert "Fixes Issue #34"

---

cadc-log/build.gradle
cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java
cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestServlet.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/SyncInput.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/SyncOutput.java
cadc-vodml/build.gradle
cadc-vodml/src/main/java/ca/nrc/cadc/vodml/VOModelReader.java
cadc-vodml/src/main/java/ca/nrc/cadc/vodml/VOModelWriter.java
cadc-vodml/src/main/resources/vo-dml-v1.0.sch.xml
cadc-vodml/src/main/resources/vo-dml-v1.0.xsd
cadc-vodml/src/test/java/ca/nrc/cadc/vodml/VOModelReaderTest.java
cadc-vodml/src/test/resources/Test-Invalid-Schematron-vodml.xml
cadc-vodml/src/test/resources/Test-Invalid-composition-vodml.xml
cadc-vodml/src/test/resources/Test-Valid-vodml-version.xml

new usage in https://github.com/pdowler/uws/tree/master/cadc-uws-server 
existing usage in https://github.com/pdowler/caom2db/tree/master/caom2-repo-server has been adapted

augment cadc-rest so it is sufficient to implement UWS async

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/FileContent.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java

Previously, it only supported Files

HttpPost supports FileContent for submitting data

---

cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestServlet.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/SyncOutput.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/FileContent.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java
cadc-util/src/main/java/ca/nrc/cadc/util/Enumerator.java

cadc-util: add binary content support to HttpPost/FileContent
cadc-rest: pass init-params not used to configure actions into base RestAction

support POST of binary content and config of RestAction

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/HttpDelete.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpDownload.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpTransfer.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpUpload.java
cadc-util/src/test/java/ca/nrc/cadc/net/HttpDeleteTest.java

removed setSSLSocketFactory from http lib because it leads to really bad code; must use Subject.doAs

added capture and access to all response headers

---

cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/util/UUIDComparator.java
cadc-util/src/test/java/ca/nrc/cadc/util/UUIDTest.java

added custom UUIDComparator to work around RFC4122-non-compliance

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/xml/W3CConstants.java
cadc-util/src/main/java/ca/nrc/cadc/xml/XmlUtil.java
cadc-util/src/main/resources/xml.xsd
cadc-util/src/test/resources/foo.xsd

XmlUtil now also adds XMLSchema to namespace cache so apps don't have to

add xml.xsd to default namespace map/cache

---

.travis.yml
cadc-log/build.gradle
cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java
cadc-log/src/main/java/ca/nrc/cadc/log/ServletLogInfo.java
cadc-log/src/main/java/ca/nrc/cadc/log/WebServiceLogInfo.java
cadc-log/src/main/java/ca/nrc/cadc/profiler/Profiler.java

fixed groupAuthorizer init bug in LogControlServlet

---

cadc-auth-restlet/build.gradle
cadc-http-client/build.gradle
cadc-keygen/build.gradle
cadc-log/build.gradle
cadc-rest/build.gradle
cadc-test-servlet/build.gradle
cadc-util/build.gradle
cadc-vodml/build.gradle

General rules applied:
* Third party libraries to fix version.
* Add max version to CAOM libraries in the form of: [x.y, x.y+1)

Dependencies versions review

---

cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/InitAction.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestServlet.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/util/MultiValuedProperties.java
cadc-util/src/main/java/ca/nrc/cadc/util/PropertiesReader.java
cadc-util/src/test/java/ca/nrc/cadc/util/PropertiesReaderTest.java

also improve PropertiesReader/MultiValuedProperties API

support for cadc-rest InitAction

---

cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/SyncInput.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpTransfer.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpUpload.java

cadc-rest: added debug logging of request headers

 fixed setting of content-length and streaming vs chunked mode 

---

cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestAction.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/util/RsaSignatureGenerator.java
cadc-util/src/main/java/ca/nrc/cadc/util/RsaSignatureVerifier.java

also an error handling change in cadc-rest that is kind of old (was in my fork) but no library version increment; can't recall what motivated that change

improve RsaSignature class usage

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/auth/SSLUtil.java
cadc-util/src/test/java/ca/nrc/cadc/xml/IterableContentTest.java

Does this need an integration test?  We could add the bouncy castle dependency and write certificates ourselves, or add some `HttpDownload` requests to pull a new cert and compare after the renew call.

Fixes #131

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/HttpDelete.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpDownload.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpGet.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpTransfer.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpUpload.java

wrap SocketTimeoutException with TransientException

HttpTransfer: added setConnectionTimeout and setReadTimeout 

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/date/DateUtil.java
cadc-util/src/test/java/ca/nrc/cadc/date/DateUtilTest.java

Added DateUtil functions to assist with FITS conversions.

---

cadc-rest/build.gradle
cadc-rest/src/main/java/ca/nrc/cadc/rest/RestServlet.java

… to allow the action to set the log start path.

CADC-9716 - set the action logInfo after setting the action syncInput

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java

removed ctor constraints rejecting empty parameter maps
made paramMap final and added getParameterMap
copy ctor arg map content instead of keep map

added HttpPost ctor

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/io/MultiBufferIO.java

added try/finally to detect possible thread leak

MultiBufferIO: set thread name for writer thread

---

cadc-util/build.gradle
cadc-util/src/intTest/java/ca/nrc/cadc/db/version/InitDatabaseTest.java
cadc-util/src/intTest/resources/dbversion.ModelVersion.sql
cadc-util/src/intTest/resources/dbversion.permissions.sql
cadc-util/src/intTest/resources/dbversion.test_table.sql
cadc-util/src/intTest/resources/dbversion.upgrade-0.2.sql
cadc-util/src/intTest/resources/dbversion.upgrade-0.3.sql
cadc-util/src/main/java/ca/nrc/cadc/db/version/InitDatabase.java
cadc-util/src/main/java/ca/nrc/cadc/db/version/KeyValueDAO.java

plus other minor tweaks that might show up in the next day so so

cadc-util-1.6.2: update a runtime log4j dep to current && InitDatabase locking

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/net/AuthChallenge.java
cadc-util/src/main/java/ca/nrc/cadc/net/HttpPost.java

added support for char[] param value in HttpPost

added AuthChallenge to parse/serialise www-authenticate challenges

---

cadc-log/README.md
cadc-log/build.gradle
cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/auth/AuthenticationUtil.java
cadc-util/src/main/java/ca/nrc/cadc/auth/ServletPrincipalExtractor.java
cadc-util/src/main/java/ca/nrc/cadc/auth/TokenValidator.java
cadc-util/src/main/java/ca/nrc/cadc/util/MultiValuedProperties.java
cadc-util/src/main/java/ca/nrc/cadc/util/PropertiesReader.java
cadc-util/src/test/java/ca/nrc/cadc/auth/TokenValidatorTest.java
cadc-util/src/test/java/ca/nrc/cadc/util/PropertiesReaderTest.java

so other challenge types can be supported in custom Authenticator

tweaks to authorization header handling

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/auth/AuthenticationUtil.java

Incorrect method called when using Authenticator.

Small fix for proper method call.

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/log/WebServiceLogInfo.java

use case: minoc PutAction to separate overhead from transfer time

add WebLogInfo.overhead time

---

cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/db/version/KeyValueDAO.java

exception thrown when ModelVersion table does not exist is different in tomcat (reason unknown)

update to KeyValueDAO detection of missing table

---

cadc-util/src/intTest/java/ca/nrc/cadc/auth/SSLUtilTest.java
cadc-util/src/intTest/java/ca/nrc/cadc/db/version/InitDatabaseTest.java
cadc-util/src/intTest/java/ca/nrc/cadc/db/version/KeyValueDAOTest.java

remove obsolete proxy cert specific tests

fix db.version tests to use same dbrc entry as DBUtilTest

---

.github/workflows/gradle.yml
cadc-util/build.gradle
cadc-util/src/main/java/ca/nrc/cadc/db/mappers/IntRowMapper.java
cadc-util/src/main/java/ca/nrc/cadc/db/mappers/JdbcMapUtil.java
cadc-util/src/main/java/ca/nrc/cadc/db/mappers/LongRowMapper.java
cadc-util/src/main/java/ca/nrc/cadc/db/mappers/TimestampRowMapper.java
cadc-util/src/main/java/org/opencadc/persist/Entity.java

moved some re-usable spring-jdbc RowMapper classes from caom2

bug fix for Entity navigating set of generic values

---

cadc-log/build.gradle
cadc-log/src/main/java/ca/nrc/cadc/log/LogControlServlet.java

with good old stdout error message and stack trace

cadc-log: added try/catch in the init method
